package startgg

// Startgg only shows (non-standard) country names (ongoing problem for years,
// probably will never be fixed), so we need this mapping to convert these
// names to alpha-2 codes.
// From https://gist.github.com/morleym/a39c43f6544a350c109c5f7b0b055155
var nameToCode = map[string]string{
	"Bangladesh":                         "bd",
	"Belgium":                            "be",
	"Burkina Faso":                       "bf",
	"Bulgaria":                           "bg",
	"Bosnia and Herzegovina":             "ba",
	"Barbados":                           "bb",
	"Wallis and Futuna":                  "wf",
	"Saint Barthelemy":                   "bl",
	"Bermuda":                            "bm",
	"Brunei":                             "bn",
	"Bolivia":                            "bo",
	"Bahrain":                            "bh",
	"Burundi":                            "bi",
	"Benin":                              "bj",
	"Bhutan":                             "bt",
	"Jamaica":                            "jm",
	"Bouvet Island":                      "bv",
	"Botswana":                           "bw",
	"Samoa":                              "ws",
	"Bonaire, Saint Eustatius and Saba ": "bq",
	"Brazil":                             "br",
	"Bahamas":                            "bs",
	"Jersey":                             "je",
	"Belarus":                            "by",
	"Belize":                             "bz",
	"Russia":                             "ru",
	"Rwanda":                             "rw",
	"Serbia":                             "rs",
	"East Timor":                         "tl",
	"Reunion":                            "re",
	"Turkmenistan":                       "tm",
	"Tajikistan":                         "tj",
	"Romania":                            "ro",
	"Tokelau":                            "tk",
	"Guinea-Bissau":                      "gw",
	"Guam":                               "gu",
	"Guatemala":                          "gt",
	"South Georgia and the South Sandwich Islands": "gs",
	"Greece":                               "gr",
	"Equatorial Guinea":                    "gq",
	"Guadeloupe":                           "gp",
	"Japan":                                "jp",
	"Guyana":                               "gy",
	"Guernsey":                             "gg",
	"French Guiana":                        "gf",
	"Georgia":                              "ge",
	"Grenada":                              "gd",
	"United Kingdom":                       "gb",
	"Gabon":                                "ga",
	"El Salvador":                          "sv",
	"Guinea":                               "gn",
	"Gambia":                               "gm",
	"Greenland":                            "gl",
	"Gibraltar":                            "gi",
	"Ghana":                                "gh",
	"Oman":                                 "om",
	"Tunisia":                              "tn",
	"Jordan":                               "jo",
	"Croatia":                              "hr",
	"Haiti":                                "ht",
	"Hungary":                              "hu",
	"Hong Kong":                            "hk",
	"Honduras":                             "hn",
	"Heard Island and McDonald Islands":    "hm",
	"Venezuela":                            "ve",
	"Puerto Rico":                          "pr",
	"Palestinian Territory":                "ps",
	"Palau":                                "pw",
	"Portugal":                             "pt",
	"Svalbard and Jan Mayen":               "sj",
	"Paraguay":                             "py",
	"Iraq":                                 "iq",
	"Panama":                               "pa",
	"French Polynesia":                     "pf",
	"Papua New Guinea":                     "pg",
	"Peru":                                 "pe",
	"Pakistan":                             "pk",
	"Philippines":                          "ph",
	"Pitcairn":                             "pn",
	"Poland":                               "pl",
	"Saint Pierre and Miquelon":            "pm",
	"Zambia":                               "zm",
	"Western Sahara":                       "eh",
	"Estonia":                              "ee",
	"Egypt":                                "eg",
	"South Africa":                         "za",
	"Ecuador":                              "ec",
	"Italy":                                "it",
	"Vietnam":                              "vn",
	"Solomon Islands":                      "sb",
	"Ethiopia":                             "et",
	"Somalia":                              "so",
	"Zimbabwe":                             "zw",
	"Saudi Arabia":                         "sa",
	"Spain":                                "es",
	"Eritrea":                              "er",
	"Montenegro":                           "me",
	"Moldova":                              "md",
	"Madagascar":                           "mg",
	"Saint Martin":                         "mf",
	"Morocco":                              "ma",
	"Monaco":                               "mc",
	"Uzbekistan":                           "uz",
	"Myanmar":                              "mm",
	"Mali":                                 "ml",
	"Macao":                                "mo",
	"Mongolia":                             "mn",
	"Marshall Islands":                     "mh",
	"Macedonia":                            "mk",
	"Mauritius":                            "mu",
	"Malta":                                "mt",
	"Malawi":                               "mw",
	"Maldives":                             "mv",
	"Martinique":                           "mq",
	"Northern Mariana Islands":             "mp",
	"Montserrat":                           "ms",
	"Mauritania":                           "mr",
	"Isle of Man":                          "im",
	"Uganda":                               "ug",
	"Tanzania":                             "tz",
	"Malaysia":                             "my",
	"Mexico":                               "mx",
	"Israel":                               "il",
	"France":                               "fr",
	"British Indian Ocean Territory":       "io",
	"Saint Helena":                         "sh",
	"Finland":                              "fi",
	"Fiji":                                 "fj",
	"Falkland Islands":                     "fk",
	"Micronesia":                           "fm",
	"Faroe Islands":                        "fo",
	"Nicaragua":                            "ni",
	"Netherlands":                          "nl",
	"Norway":                               "no",
	"Namibia":                              "na",
	"Vanuatu":                              "vu",
	"New Caledonia":                        "nc",
	"Niger":                                "ne",
	"Norfolk Island":                       "nf",
	"Nigeria":                              "ng",
	"New Zealand":                          "nz",
	"Nepal":                                "np",
	"Nauru":                                "nr",
	"Niue":                                 "nu",
	"Cook Islands":                         "ck",
	"Kosovo":                               "xk",
	"Ivory Coast":                          "ci",
	"Switzerland":                          "ch",
	"Colombia":                             "co",
	"China":                                "cn",
	"Cameroon":                             "cm",
	"Chile":                                "cl",
	"Cocos Islands":                        "cc",
	"Canada":                               "ca",
	"CA":                                   "ca",
	"Republic of the Congo":                "cg",
	"Central African Republic":             "cf",
	"Democratic Republic of the Congo":     "cd",
	"Czech Republic":                       "cz",
	"Cyprus":                               "cy",
	"Christmas Island":                     "cx",
	"Costa Rica":                           "cr",
	"Curacao":                              "cw",
	"Cape Verde":                           "cv",
	"Cuba":                                 "cu",
	"Swaziland":                            "sz",
	"Syria":                                "sy",
	"Sint Maarten":                         "sx",
	"Kyrgyzstan":                           "kg",
	"Kenya":                                "ke",
	"South Sudan":                          "ss",
	"Suriname":                             "sr",
	"Kiribati":                             "ki",
	"Cambodia":                             "kh",
	"Saint Kitts and Nevis":                "kn",
	"Comoros":                              "km",
	"Sao Tome and Principe":                "st",
	"Slovakia":                             "sk",
	"South Korea":                          "kr",
	"Slovenia":                             "si",
	"North Korea":                          "kp",
	"Kuwait":                               "kw",
	"Senegal":                              "sn",
	"San Marino":                           "sm",
	"Sierra Leone":                         "sl",
	"Seychelles":                           "sc",
	"Kazakhstan":                           "kz",
	"Cayman Islands":                       "ky",
	"Singapore":                            "sg",
	"Sweden":                               "se",
	"Sudan":                                "sd",
	"Dominican Republic":                   "do",
	"Dominica":                             "dm",
	"Djibouti":                             "dj",
	"Denmark":                              "dk",
	"British Virgin Islands":               "vg",
	"Germany":                              "de",
	"Yemen":                                "ye",
	"Algeria":                              "dz",
	"United States":                        "us",
	"US":                                   "us",
	"Uruguay":                              "uy",
	"Mayotte":                              "yt",
	"United States Minor Outlying Islands": "um",
	"Lebanon":                              "lb",
	"Saint Lucia":                          "lc",
	"Laos":                                 "la",
	"Tuvalu":                               "tv",
	"Taiwan":                               "tw",
	"Trinidad and Tobago":                  "tt",
	"Turkey":                               "tr",
	"Sri Lanka":                            "lk",
	"Liechtenstein":                        "li",
	"Latvia":                               "lv",
	"Tonga":                                "to",
	"Lithuania":                            "lt",
	"Luxembourg":                           "lu",
	"Liberia":                              "lr",
	"Lesotho":                              "ls",
	"Thailand":                             "th",
	"French Southern Territories":          "tf",
	"Togo":                                 "tg",
	"Chad":                                 "td",
	"Turks and Caicos Islands":             "tc",
	"Libya":                                "ly",
	"Vatican":                              "va",
	"Saint Vincent and the Grenadines":     "vc",
	"United Arab Emirates":                 "ae",
	"Andorra":                              "ad",
	"Antigua and Barbuda":                  "ag",
	"Afghanistan":                          "af",
	"Anguilla":                             "ai",
	"U.S. Virgin Islands":                  "vi",
	"Iceland":                              "is",
	"Iran":                                 "ir",
	"Armenia":                              "am",
	"Albania":                              "al",
	"Angola":                               "ao",
	"Antarctica":                           "aq",
	"American Samoa":                       "as",
	"Argentina":                            "ar",
	"Australia":                            "au",
	"Austria":                              "at",
	"Aruba":                                "aw",
	"India":                                "in",
	"Aland Islands":                        "ax",
	"Azerbaijan":                           "az",
	"Ireland":                              "ie",
	"Indonesia":                            "id",
	"Ukraine":                              "ua",
	"Qatar":                                "qa",
	"Mozambique":                           "mz",
	"Wales":                                "gb-wls",
	"Scotland":                             "gb-sct",
}
